"""
ChromaDB persistent collection for user memory.

Manages the user_facts collection in ChromaDB with persistent
storage at ./chroma_user_memory.
"""

import logging
from pathlib import Path
from typing import Optional, List, Dict, Any
import time
import chromadb
from rag.embedder import ChromaEmbeddingFunction

logger = logging.getLogger(__name__)

CHROMA_PATH = Path(__file__).parent.parent / "chroma_user_memory"
COLLECTION_NAME = "user_facts"

class UserMemoryStore:
    """Persistent ChromaDB collection for user facts, distinct from pokemon knowledge."""

    def __init__(self, path: Optional[str] = None):
        """
        Initialize the user memory store.

        Args:
            path: Custom path for ChromaDB storage (default: ./chroma_user_memory)
        """
        store_path = path or str(CHROMA_PATH)
        self.client = chromadb.PersistentClient(path=store_path)
        self.embedding_fn = ChromaEmbeddingFunction()
        self.collection = self.client.get_or_create_collection(
            name=COLLECTION_NAME,
            embedding_function=self.embedding_fn,
            metadata={"hnsw:space": "cosine"},
        )
        logger.info(
            f"User memory store initialized: {self.collection.count()} facts "
            f"in {store_path}"
        )

    def add_fact(self, fact: str, category: str, id_override: Optional[str] = None) -> str:
        """
        Add a new fact to the user memory.

        Args:
            fact: The raw fact text (e.g. "User's favorite Pokemon is Charizard")
            category: Fact category (e.g. 'identity', 'team', 'preference')
            id_override: Optional ID, otherwise autogenerated

        Returns:
            The ID of the added fact.
        """
        timestamp = str(time.time())
        fact_id = id_override or f"fact_{int(time.time() * 1000)}"
        
        metadata = {
            "category": category,
            "timestamp": timestamp,
            "deprecated": "false",
        }
        
        self.collection.upsert(
            ids=[fact_id],
            documents=[fact],
            metadatas=[metadata]
        )
        logger.info(f"Added/Updated user fact [{category}]: {fact} (ID: {fact_id})")
        return fact_id

    def get_relevant_facts(self, query: str, k: int = 5) -> List[Dict[str, Any]]:
        """
        Retrieve relevant facts from user memory matching a query semantically.

        Args:
            query: Semantic search query
            k: Max number of facts to return

        Returns:
            List of facts matching query (excluding deprecated facts).
        """
        if self.collection.count() == 0:
            return []

        # Find only non-deprecated facts
        results = self.collection.query(
            query_texts=[query],
            n_results=min(k, self.collection.count()),
            where={"deprecated": "false"}
        )

        output = []
        if results and results["ids"] and results["ids"][0]:
            for i in range(len(results["ids"][0])):
                output.append({
                    "id": results["ids"][0][i],
                    "fact": results["documents"][0][i] if results.get("documents") else "",
                    "metadata": results["metadatas"][0][i] if results.get("metadatas") else {},
                    "distance": results["distances"][0][i] if results.get("distances") else 0.0,
                })
        return output

    def list_all_facts(self, include_deprecated: bool = False) -> List[Dict[str, Any]]:
        """
        List all facts stored in the user memory.

        Args:
            include_deprecated: Whether to include deprecated facts

        Returns:
            List of all facts.
        """
        if self.collection.count() == 0:
            return []

        if include_deprecated:
            results = self.collection.get()
        else:
            results = self.collection.get(where={"deprecated": "false"})

        output = []
        if results and results["ids"]:
            for i in range(len(results["ids"])):
                output.append({
                    "id": results["ids"][i],
                    "fact": results["documents"][i] if results.get("documents") else "",
                    "metadata": results["metadatas"][i] if results.get("metadatas") else {},
                })
        return output

    def delete_fact(self, fact_id: str) -> None:
        """Delete a fact completely from memory."""
        self.collection.delete(ids=[fact_id])
        logger.info(f"Deleted user fact ID: {fact_id}")

    def update_fact(self, fact_id: str, new_fact: str, category: str) -> None:
        """Manually update an existing fact's contents."""
        metadata = {
            "category": category,
            "timestamp": str(time.time()),
            "deprecated": "false"
        }
        self.collection.update(
            ids=[fact_id],
            documents=[new_fact],
            metadatas=[metadata]
        )
        logger.info(f"Manually updated user fact ID {fact_id}: {new_fact}")

    def clear(self) -> None:
        """Clear all facts."""
        self.client.delete_collection(COLLECTION_NAME)
        self.collection = self.client.get_or_create_collection(
            name=COLLECTION_NAME,
            embedding_function=self.embedding_fn,
            metadata={"hnsw:space": "cosine"},
        )
        logger.info("User memory cleared")
